// Casper Network Configuration
export const CASPER_NODE_ADDRESS = process.env.NEXT_PUBLIC_CASPER_LIVENET_NODE_ADDRESS!;
export const CASPER_CLOUD_ENDPOINT = process.env.NEXT_PUBLIC_CASPER_CLOUD_ENDPOINT!;
export const CASPER_CHAIN_NAME = process.env.NEXT_PUBLIC_CASPER_LIVENET_CHAIN_NAME!;
export const CASPER_EVENTS_URL = process.env.NEXT_PUBLIC_CASPER_LIVENET_EVENTS_URL!;

// Contract Addresses
export const PRICE_ORACLE_CONTRACT = process.env.NEXT_PUBLIC_PRICE_ORACLE!;
export const VALIDATOR_REGISTRY_CONTRACT = process.env.NEXT_PUBLIC_VALIDATOR_REGISTRY!;
export const CUSD_CONTRACT = process.env.NEXT_PUBLIC_CUSD!;
export const YSCSPR_CONTRACT = process.env.NEXT_PUBLIC_YSCSPR!;
export const LIQUID_STAKING_CONTRACT = process.env.NEXT_PUBLIC_LIQUID_STAKING!;
export const STAYER_VAULT_CONTRACT = process.env.NEXT_PUBLIC_STAYER_VAULT!;
