// Casper Network Configuration
export const CASPER_NODE_ADDRESS = process.env.NEXT_PUBLIC_CASPER_LIVENET_NODE_ADDRESS!;
export const CASPER_CLOUD_ENDPOINT = process.env.NEXT_PUBLIC_CASPER_CLOUD_ENDPOINT!;
export const CASPER_API_URL = process.env.NEXT_PUBLIC_CASPER_API_URL!;
export const CASPER_CHAIN_NAME = process.env.NEXT_PUBLIC_CASPER_LIVENET_CHAIN_NAME!;
export const CASPER_EVENTS_URL = process.env.NEXT_PUBLIC_CASPER_LIVENET_EVENTS_URL!;
export const CASPER_NODE_URL = process.env.NEXT_PUBLIC_NODE_URL!;
export const CASPER_EXPLORER_URL = process.env.NEXT_PUBLIC_CASPER_LIVE_EXPLORER_URL!;

export const CASPER_CLICK_APP_ID = process.env.NEXT_PUBLIC_CASPER_CLICK_APP_ID!;

// Contract Addresses
export const PRICE_ORACLE_CONTRACT = process.env.NEXT_PUBLIC_PRICE_ORACLE!;
export const VALIDATOR_REGISTRY_CONTRACT = process.env.NEXT_PUBLIC_VALIDATOR_REGISTRY!;
export const CUSD_CONTRACT = process.env.NEXT_PUBLIC_CUSD!;
export const YSCSPR_CONTRACT = process.env.NEXT_PUBLIC_YSCSPR!;
export const LIQUID_STAKING_CONTRACT = process.env.NEXT_PUBLIC_LIQUID_STAKING!;
export const STAYER_VAULT_CONTRACT = process.env.NEXT_PUBLIC_STAYER_VAULT!;

export const LIQUID_STAKING_CONSTANTS = {
  MIN_STAKE_CSPR: 10,
  MAX_STAKE_CSPR: 1000000,
  MIN_UNSTAKE_CSPR: 5,
  MAX_UNSTAKE_CSPR: 500000,
};